![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on! 

In [316]:
import sys
import numpy as np

## Basic Numpy Arrays

In [317]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [318]:
a = np.array([1, 2, 3, 4])

In [319]:
b = np.array([0, .5, 1, 1.5, 2])

In [320]:
a[0], a[1]

(np.int64(1), np.int64(2))

In [321]:
a[0:]

array([1, 2, 3, 4])

Slice

In [322]:
a[1:3]

array([2, 3])

In [323]:
a[1:-1]

array([2, 3])

In [324]:
a[::2]

array([1, 3])

In [325]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [326]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

Mult selection

In [327]:
b[[0, 2, -1]]

array([0., 1., 2.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Types

In [328]:
a

array([1, 2, 3, 4])

In [329]:
a.dtype

dtype('int64')

In [330]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [331]:
b.dtype

dtype('float64')

In [332]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [333]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [334]:
c = np.array(['a', 'b', 'c'])

In [335]:
c.dtype

dtype('<U1')

In [336]:
d = np.array([{'a': 1, 'a': 2}, sys])

In [337]:
d.dtype

dtype('O')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dimensions and shapes

In [338]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [339]:
A.shape

(2, 3)

In [340]:
A.ndim

2

In [341]:
A.size

6

In [342]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1],
    ]
])

In [343]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [344]:
B.shape

(2, 2, 3)

In [345]:
B.ndim

3

In [346]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [458]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [459]:
C.dtype

dtype('int64')

In [460]:
C.shape

(2, 2, 3)

In [461]:
C.size

12

In [462]:
type(C[0])

numpy.ndarray

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexing and Slicing of Matrices

In [352]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [353]:
A[1]

array([4, 5, 6])

In [354]:
A[1][0]

np.int64(4)

In [355]:
# A[d1, d2, d3, d4]

In [356]:
A[1, 0]

np.int64(4)

In [357]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [358]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [359]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [360]:
A[:2, 2:]

array([[3],
       [6]])

In [361]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [362]:
A[1] = np.array([10, 10, 10])

In [363]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [364]:
A[2] = 99

In [365]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

In [366]:
a = np.array([1, 2, 3, 4])

In [367]:
a.sum()

np.int64(10)

In [368]:
a.mean()

np.float64(2.5)

In [369]:
a.std()

np.float64(1.118033988749895)

In [370]:
a.var()

np.float64(1.25)

In [371]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [372]:
A.sum()

np.int64(45)

In [373]:
A.mean()

np.float64(5.0)

In [374]:
A.std()

np.float64(2.581988897471611)

In [375]:
A.sum(axis=0)

array([12, 15, 18])

In [376]:
A.sum(axis=1)

array([ 6, 15, 24])

In [377]:
A.mean(axis=0)

array([4., 5., 6.])

In [378]:
A.mean(axis=1)

array([2., 5., 8.])

In [379]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [380]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

In [381]:
a = np.arange(5)

In [382]:
a

array([0, 1, 2, 3, 4])

In [383]:
a + 20

array([20, 21, 22, 23, 24])

In [384]:
a * 10

array([ 0, 10, 20, 30, 40])

In [385]:
a

array([0, 1, 2, 3, 4])

In [386]:
a += 100

In [387]:
a

array([100, 101, 102, 103, 104])

In [388]:
l = [0, 1, 2, 3]

In [389]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [390]:
a = np.arange(4)

In [391]:
a

array([0, 1, 2, 3])

In [392]:
b = np.array([10, 10, 10, 10])

In [393]:
b

array([10, 10, 10, 10])

In [394]:
a + b

array([10, 11, 12, 13])

In [395]:
a * b

array([ 0, 10, 20, 30])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Boolean arrays
_(Also called masks)_

In [396]:
a = np.arange(4)

In [397]:
a

array([0, 1, 2, 3])

In [398]:
a[0], a[-1]

(np.int64(0), np.int64(3))

In [399]:
a[[0, -1]]

array([0, 3])

In [400]:
a[[True, False, False, True]]

array([0, 3])

In [401]:
a

array([0, 1, 2, 3])

In [402]:
a >= 2

array([False, False,  True,  True])

In [403]:
a[a >= 2]

array([2, 3])

In [404]:
a.mean()

np.float64(1.5)

In [405]:
a[a > a.mean()]

array([2, 3])

In [406]:
a[~(a > a.mean())]

array([0, 1])

In [407]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [408]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [409]:
A = np.random.randint(100, size=(3, 3))

In [410]:
A

array([[31, 70, 35],
       [60, 64,  6],
       [18, 25, 14]])

In [411]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([31, 35, 64, 18, 14])

In [412]:
A > 30

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [413]:
A[A > 30]

array([31, 70, 35, 60, 64])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra

In [414]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [415]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [416]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [417]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [418]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [419]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [420]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Size of objects in Memory

### Int, floats

In [421]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [422]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [423]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [424]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [425]:
np.dtype(float).itemsize

8

### Lists are even larger

In [426]:
# A one-element list
sys.getsizeof([1])

64

In [427]:
# An array of one element in numpy
np.array([1]).nbytes

8

### And performance is also important

In [428]:
l = list(range(100000))

In [429]:
a = np.arange(100000)

In [430]:
%time np.sum(a ** 2)

CPU times: user 1.34 ms, sys: 0 ns, total: 1.34 ms
Wall time: 980 μs


np.int64(333328333350000)

In [431]:
%time sum([x ** 2 for x in l])

CPU times: user 12.2 ms, sys: 5.08 ms, total: 17.3 ms
Wall time: 17.2 ms


333328333350000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Useful Numpy functions

### `random` 

In [432]:
np.random.random(size=2)

array([0.17315595, 0.72580332])

In [433]:
np.random.normal(size=2)

array([ 0.7765616 , -0.05191633])

In [434]:
np.random.rand(2, 4)

array([[0.9286558 , 0.34078177, 0.33162606, 0.32527414],
       [0.19449206, 0.21989949, 0.18428504, 0.09659625]])

---
### `arange`

In [435]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [436]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [437]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---
### `reshape`

In [438]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [439]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---
### `linspace`

In [440]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [441]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [442]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

---
### `zeros`, `ones`, `empty`

In [443]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [444]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [445]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [446]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [447]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [448]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [449]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

---
### `identity` and `eye`

In [450]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [451]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [452]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [453]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [454]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [455]:
"Hello World"[6]

'W'

In [456]:
A = np.array([
['a', 'b', 'c'],
['d', 'e', 'f'],
['g', 'h', 'i']])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [457]:
a = np.arange(5)
print(a)
print(a <= 3)

[0 1 2 3 4]
[ True  True  True  True False]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)